const people = [
  {
    id: 1,
    name: "Nguyễn Văn Sơn",
    group: 1,
    isMonitor: false,
  },
  {
    id: 2,
    name: "Nguyễn Hữu Ánh",
    group: 1,
    isMonitor: false,
  },
  {
    id: 3,
    name: "Trần Mạnh Quân",
    group: 4,
    isMonitor: true,
  },
  {
    id: 4,
    name: "Hà Quốc Tuấn",
    group: 3,
    isMonitor: true,
  },
  {
    id: 5,
    name: "Hoàng Ngọc Thành",
    group: 1,
    isMonitor: false,
  },
  {
    id: 6,
    name: "Vũ Thị Thu Hà",
    group: 2,
    isMonitor: false,
  },
  {
    id: 7,
    name: "Phan Văn Trung",
    group: 2,
    isMonitor: false,
  },
  {
    id: 8,
    name: "Nguyễn Cao Hoàng",
    group: 2,
    isMonitor: false,
  },
  {
    id: 9,
    name: "Phùng Đắc Nhật Minh",
    group: 5,
    isMonitor: true,
  },
  {
    id: 10,
    name: "Lê Việt Dũng",
    group: 1,
    isMonitor: true,
  },
  {
    id: 11,
    name: "Đỗ Chí Công",
    group: 2,
    isMonitor: false,
  },
  {
    id: 12,
    name: "Trần Công Tâm",
    group: 3,
    isMonitor: false,
  },
  {
    id: 13,
    name: "Trương Thanh Tùng",
    group: 3,
    isMonitor: false,
  },
  {
    id: 14,
    name: "Tạ Đức Chiến",
    group: 3,
    isMonitor: false,
  },
  {
    id: 15,
    name: "Nguyễn Trọng Vĩnh",
    group: 3,
    isMonitor: false,
  },
  {
    id: 16,
    name: "Ngô Chung Á Âu",
    group: 4,
    isMonitor: false,
  },
  {
    id: 17,
    name: "Trần Thị Khánh Linh",
    group: 2,
    isMonitor: true,
  },
  {
    id: 18,
    name: "Phan Tiến Thánh",
    group: 4,
    isMonitor: false,
  },
  {
    id: 19,
    name: "Đỗ Văn Huy",
    group: 4,
    isMonitor: false,
  },
  {
    id: 20,
    name: "Nguyễn Trung Đức",
    group: 5,
    isMonitor: false,
  },
  {
    id: 21,
    name: "Nguyễn Trung Nam",
    group: 5,
    isMonitor: false,
  },
  {
    id: 22,
    name: "Trần Quốc Toàn",
    group: 5,
    isMonitor: false,
  },
];
export default people;
