const stuList = [
    {id: 1,name: "Nguyễn Văn Sơn",group: 1,lead: 0}, 
    {id:2,name: "Nguyễn Hữu Ánh",group: 1,lead: 0},
    {id: 3,name: "Trần Mạnh Quân",group: 4,lead: 1},
    {id:4,name: "Hà Quốc Tuấn",group: 3,lead: 1},
    {id: 5,name: "Hoàng Ngọc Thành",group: 1,lead: 0},
    {id: 6,name: "Vũ Thị Thu Hà",group: 2,lead: 0},
    {id: 7,name: "Phan Văn Trung",group: 2,lead: 0},
    {id: 8,name: "Nguyễn Cao Hoàng",group: 2,lead: 0},
    {id: 9,name: "Phùng Đắc Nhật Minh",group: 5,lead: 1},
    {id: 10,name: "Lê Việt Dũng",group: 1,lead: 1},
    {id: 11,name: "Đỗ Chí Công",group: 2,lead: 0},
    {id: 12,name: "Trần Công Tâm",group: 3,lead: 0},
    {id: 13,name: "Trương Thanh Tùng",group: 3,lead: 0},
    {id: 14,name: "Tạ Đức Chiến",group: 3,lead: 0},
    {id: 15,name: "Nguyễn Trọng Vĩnh",group: 3,lead: 0},
    {id: 16,name: "Ngô Chung Á Âu",group: 4,lead: 0},
    {id: 17,name: "Trần Thị Khánh Linh",group: 2,lead: 1},
    {id: 18,name: "Phan Tiến Thành",group: 4,lead: 0},
    {id: 19,name: "Đỗ Văn Huy",group: 4,lead: 0},
    {id: 20,name: "Nguyễn Trung Đức",group: 5,lead: 0},
    {id: 21,name: "Nguyễn Trung Nam",group: 5,lead: 0},
    {id: 22,name: "Trần Quốc Toàn",group: 5,lead: 0},
]

export default stuList;