var arrStudentLabs = [
 {
   id: "01",
   name: "Nguyễn Văn Sơn",
   position: "Thành viên",
   groupNumber: "-1",
 },
 {
   id: "02",
   name: "Nguyễn Hữu Ánh",
   position: "Thành viên",
   groupNumber: "1",
 },
 {
   id: "03",
   name: "Trần Mạnh Quân",
   position: "Trưởng nhóm",
   groupNumber: "4",
 },
 {
   id: "04",
   name: "Hà Quốc Tuấn",
   position: "Trưởng nhóm",
   groupNumber: "3",
 },
 {
   id: "05",
   name: "Hoàng Ngọc Thành",
   position: "Thành viên",
   groupNumber: "1",
 },
 {
   id: "06",
   name: "Vũ Thị Thu Hà",
   position: "Thành viên",
   groupNumber: "2",
 },
 {
   id: "07",
   name: "Phan Văn Trung",
   position: "Thành viên",
   groupNumber: "2",
 },
 {
   id: "08",
   name: "Nguyễn Cao Hoàng",
   position: "Thành viên",
   groupNumber: "2",
 },
 {
   id: "09",
   name: "Phùng Đắc Nhật Minh",
   position: "Trưởng nhóm",
   groupNumber: "5",
 },
 {
   id: "10",
   name: "Lê Việt Dũng",
   position: "Trưởng nhóm",
   groupNumber: "1",
 },
 {
   id: "11",
   name: "Đỗ Chí Dũng",
   position: "Thành viên",
   groupNumber: "2",
 },
 {
   id: "12",
   name: "Trần Công Tâm",
   position: "Thành viên",
   groupNumber: "3",
 },
 {
   id: "13",
   name: "Trương Thanh Tùng",
   position: "Thành viên",
   groupNumber: "3",
 },
 {
   id: "14",
   name: "Tạ Đức Chiến",
   position: "Thành viên",
   groupNumber: "3",
 },
 {
   id: "15",
   name: "Nguyễn Trọng Vinh",
   position: "Thành viên",
   groupNumber: "3",
 },
 {
   id: "16",
   name: "Ngô Chung Á Âu",
   position: "Thành viên",
   groupNumber: "4",
 },
 {
   id: "17",
   name: "Trần Thị Khánh Linh",
   position: "Trưởng nhóm",
   groupNumber: "2",
 },
 {
   id: "18",
   name: "Phan Tiến Thành",
   position: "Thành viên",
   groupNumber: "4",
 },
 {
   id: "19",
   name: "Đỗ Văn Huy",
   position: "Thành viên",
   groupNumber: "4",
 },
 {
   id: "20",
   name: "Nguyễn Trung Đức",
   position: "Thành viên",
   groupNumber: "5",
 },
 {
   id: "21",
   name: "Nguyễn Trung Nam",
   position: "Thành viên",
   groupNumber: "5",
 },
 {
   id: "22",
   name: "Trần Quốc Toàn",
   position: "Thành viên",
   groupNumber: "5",
 },
];
console.table(arrStudentLabs);
export default arrStudentLabs;